### ISSUE TITLE
Usage of Wire library.

### ISSUE THREAD

**Issue by Koepel** [Infineon/RGB-LED-Lighting-Shield-XMC1202#1]
In the file 'src/RGBLEDLighting.cpp", the reading and writing is mixed.
This is the wrong sequence: beginTransmission - write - requestFrom - available - read - endTransmission.

To write something, the sequence should be: _beginTransmission_ - _write_ - _endTransmission_.
To read something, it is: _requestFrom_ (after that _available_ and _read_ may be used).

It is in the functions: `I2CREAD()`, `I2CREAD_DIRECTACCESS()` and `I2CSAVEPARAM()`.
See also my [alternative explanation of the functions of the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library).

**Comment by ederjc** [comment]
Thanks for your feedback! We will check that and come back to you.

**Comment by ArkajyotiChatterjee** [comment]
Hello Koepel,
Yes, we can send the address of the register directly using requestFrom command. Because the requestFrom definition has the beginTransmission.write(address) & endTransmission logic inside it only.
In any case, inside the I2CREAD the definition is like this:
`unsigned int InfineonRGB:: I2CREAD (unsigned int Address, unsigned int Command) // Returns data sent by slave
{
  int i = 0;
  unsigned int lowerSLAD = (unsigned int) (Address & 0x00FF);
  unsigned int upperSLAD = Address >> 8;
  upperSLAD |= 0x79;

  Wire.beginTransmission(byte(upperSLAD)); // Red
  Wire.write(byte(lowerSLAD));
  Wire.write(byte(Command));
  Wire.endTransmission(false); // false for Repeated Start

  Wire.beginTransmission(byte(upperSLAD));
  Wire.write(byte(lowerSLAD));
  Wire.requestFrom(upperSLAD, 2, true);
  unsigned int data = 0;

  while (Wire.available())   // slave may send less than requested. Print out received data byte
  {
    message = 1;
    c[i] = Wire.read(); // receive a byte as character
    i++;

  }
  Wire.endTransmission(true);

  data = c[1]; // write data to serial monitor. c[1] is higher byte
  data = (data << 8) | c[0];  // shift left and combine with lower byte
  //Serial.print("0x");
  if (data < 0x1000)
    //Serial.print("0");
    //Serial.println(data, HEX);
    return data;
}`

So we are beginning transmission and then sending the command(ie the register address) and then asking the bus to be open for a repeated start.
After that, we are again beginning the transmission and then calling Wire.requestFrom and finally ending it with endTransmission.
The modified code should be -->
`unsigned int InfineonRGB:: I2CREAD (unsigned int Address, unsigned int Command) // Returns data sent by slave
{
  int i = 0;
  unsigned int lowerSLAD = (unsigned int) (Address & 0x00FF);
  unsigned int upperSLAD = Address >> 8;
  upperSLAD |= 0x79;

  Wire.beginTransmission(byte(upperSLAD)); // Red
  Wire.write(byte(lowerSLAD));
  Wire.write(byte(Command));
  Wire.endTransmission(false); // false for Repeated Start

/*   Wire.beginTransmission(byte(upperSLAD));
  Wire.write(byte(lowerSLAD)); */
  Wire.requestFrom(upperSLAD, 2, true);
  unsigned int data = 0;

  while (Wire.available())   // slave may send less than requested. Print out received data byte
  {
    message = 1;
    c[i] = Wire.read(); // receive a byte as character
    i++;

  }
 /*  Wire.endTransmission(true); */

  data = c[1]; // write data to serial monitor. c[1] is higher byte
  data = (data << 8) | c[0];  // shift left and combine with lower byte
  //Serial.print("0x");
  if (data < 0x1000)
    //Serial.print("0");
    //Serial.println(data, HEX);
    return data;
}
`
The modification is done as the requestFrom definition contains the call to beginTransmission. write & endTransmission.
I just checked and it seems to be working fine.
But, now my question is this doesn't seem to be a big error; the bus transmission and address handshaking is happening twice in place of once, does this warranties a Version upgrade? 
What do you think @KOMsandFriends ?

Anyway, @Koepel please do reach back to me with your comments regarding my explanation.
Regards,

**Comment by Koepel** [comment]
The `Wire.requestFrom()` does **not** call `Wire.beginTransmission()` or `Wire.endTransmission()`.

The Arduino Due has hardware to write the register address and read the data from that register with a single command. The Arduino team decided to implement that in software in the AVR Wire library as well. That is the [undocumented requestfrom function](https://github.com/arduino/ArduinoCore-avr/blob/master/libraries/Wire/src/Wire.cpp#L89) with the many parameter.
The `Wire.beginTransmission()` and `Wire.endTransmission()` are only used for writing the register address and only with the supplied parameter for the register address. The indents in that undocumented function are wrong, but you can see that when `isize` is zero, the writing of the register is skipped.
All the other normal `Wire.requestFrom()` functions set the `isize` and the register address to zero.

Other Wire (compatible) libraries do other things, that is okay as long as they follow the official documentation. I suggest you should stay close to the official documentation as well to avoid troubles.

Because the official documentation can be confusing, I did not only write a [alternative explanation of the functions of the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library), but also a page about [common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes).
I have written on that page if those mistakes are bad or not.

The code as it is at the moment might cause troubles with an other Wire (compatible) libraries, or when the Wire library is updated.
My problem is that it will copied by many others and I have to write many issues about the wrong use of the Wire library!

May I go on ?
The Slave does not really send less than requested. If the Slave sends less bytes, then the Master does not know that and keeps on reading the requested bytes. The Master will never know that the last bytes are not valid. 
The Wire library can detect a bus collision and then stop the I2C bus activity. At this moment the Wire library will tell that zero bytes are received with a I2C bus problem.
The most elegant solution (in my opinion) is to check if everything is okay, and only then read all the bytes:

```
unsigned int data = 0;        // set default to zero, in case of I2C bus errors
Wire.requestFrom(upperSLAD, 2, true);   // request 2 bytes, send stop.
if (Wire.available() == 2)    // received the number of requested bytes ?
{
  data = (unsigned int) Wire.read();   // lsb first
  data |= (unsigned int) Wire.read() << 8;
}
```
By first checking the `Wire.available()` and be sure that there are two bytes, then the `Wire.read()` returns valid data and will not return -1.
Combining the bytes into a single 16-bit variable can be done in different ways, I just choose this way.
Instead of calling `Wire.available()`, also the return value of `Wire.requestFrom()` can be used.
